### ISSUE TITLE
Clarify Nucleo vs Disco

### ISSUE THREAD

**Issue by hugovincent** [ARMmbed/target-st-stm32f429i-disco#5]
The language in target.json talks about Nucleo, but there is not (yet?) any Nucleo board for the F429. That plus the module name suggests this is actually for the Discovery board, and the target.json needs updating.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-831

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-987
